#!/bin/bash

# $1 is the R script to run

touch submit
cat > submit << EOL
#!/bin/bash
#$ -M patr1ckm.crc@gmail.com	 # Email address for job notification
#$ -m a		 # Send mail when job begins, ends and aborts
#$ -pe smp 1           # environment and legal core size
#$ -q *@@daccss		 # Specify queue
#$ -N patr1ckm	         # Specify job name
#$ -t 1         # number of reps
#$ -o SGE_Output
Rscript $1
EOL

mkdir SGE_Output



